"""SME Research Assistant - Core Module"""

from .interfaces import (
    Document,
    Chunk,
    RetrievalResult,
    GenerationResult,
    QueryContext,
    DocumentParser,
    TextChunker,
    Embedder,
    VectorStore,
    KeywordIndex,
    Reranker,
    LLMClient,
    Cache,
    MetricsCollector,
)

from .exceptions import (
    SMEBaseException,
    IngestionError,
    PDFExtractionError,
    InvalidPDFError,
    DuplicateDocumentError,
    IndexingError,
    EmbeddingError,
    VectorStoreError,
    RetrievalError,
    NoResultsError,
    GenerationError,
    LLMConnectionError,
    LLMTimeoutError,
    SecurityError,
    AuthenticationError,
    InputValidationError,
    CacheError,
    ConfigurationError,
    CircuitOpenError,
)

__all__ = [
    # Data classes
    "Document",
    "Chunk", 
    "RetrievalResult",
    "GenerationResult",
    "QueryContext",
    # Interfaces
    "DocumentParser",
    "TextChunker",
    "Embedder",
    "VectorStore",
    "KeywordIndex",
    "Reranker",
    "LLMClient",
    "Cache",
    "MetricsCollector",
    # Exceptions
    "SMEBaseException",
    "IngestionError",
    "PDFExtractionError",
    "InvalidPDFError",
    "DuplicateDocumentError",
    "IndexingError",
    "EmbeddingError",
    "VectorStoreError",
    "RetrievalError",
    "NoResultsError",
    "GenerationError",
    "LLMConnectionError",
    "LLMTimeoutError",
    "SecurityError",
    "AuthenticationError",
    "InputValidationError",
    "CacheError",
    "ConfigurationError",
    "CircuitOpenError",
]
