#!/bin/bash
# SME Research Assistant — First-Time Production Setup
# Run this ONCE before 'docker compose up' on a new installation.
#
# This script:
# 1. Generates a secure JWT secret
# 2. Collects your API credentials
# 3. Creates the .env file
# 4. Optionally creates the first admin user
#
# Usage: bash scripts/setup.sh

set -e

ENV_FILE=".env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Change to project root
cd "$PROJECT_ROOT"

echo "==========================================="
echo "  SME Research Assistant — First-Time Setup"
echo "==========================================="
echo ""

# ── Step 1: Check if already configured ──
if [ -f "$ENV_FILE" ]; then
    echo "Warning: .env file already exists."
    read -p "Overwrite? (y/N): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "Setup cancelled. Your existing .env was preserved."
        exit 0
    fi
    # Backup existing .env
    cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "Backed up existing .env"
fi

# ── Step 2: Generate JWT Secret ──
if command -v openssl &> /dev/null; then
    JWT_SECRET=$(openssl rand -hex 32)
else
    # Fallback for systems without openssl
    JWT_SECRET=$(head -c 32 /dev/urandom | xxd -p | tr -d '\n')
fi
echo "Generated secure JWT_SECRET (64 hex characters)"

# ── Step 3: Collect User Credentials ──
echo ""
echo "── API Credentials ──"
echo "These are used to query academic paper databases."
echo ""

read -p "Your email address (for API identification): " USER_EMAIL
while [ -z "$USER_EMAIL" ]; do
    echo "Email is required for API rate limiting."
    read -p "Your email address: " USER_EMAIL
done

echo ""
echo "Get your OpenAlex API key at: https://openalex.org/"
read -p "OpenAlex API key: " OPENALEX_KEY

echo ""
echo "Get your Semantic Scholar API key at: https://www.semanticscholar.org/product/api"
read -p "Semantic Scholar API key: " S2_KEY

# ── Step 4: Dashboard Admin Account ──
echo ""
echo "── Dashboard Admin Account ──"
echo "This account will have full access to the dashboard."
echo ""

read -p "Admin username: " ADMIN_USER
while [ -z "$ADMIN_USER" ]; do
    echo "Username is required."
    read -p "Admin username: " ADMIN_USER
done

while true; do
    read -sp "Admin password (min 12 characters): " ADMIN_PASS
    echo ""

    if [ ${#ADMIN_PASS} -lt 12 ]; then
        echo "Password must be at least 12 characters. Please try again."
        continue
    fi

    read -sp "Confirm password: " ADMIN_PASS_CONFIRM
    echo ""

    if [ "$ADMIN_PASS" != "$ADMIN_PASS_CONFIRM" ]; then
        echo "Passwords do not match. Please try again."
        continue
    fi

    break
done

# ── Step 5: Streamlit Password ──
echo ""
echo "── Streamlit UI Password ──"
echo "This protects the research assistant interface at http://localhost:8502"
echo ""

read -sp "Streamlit UI password: " STREAMLIT_PASS
echo ""

# ── Step 6: Write .env ──
cat > "$ENV_FILE" << EOF
# SME Research Assistant — Environment Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE TO GIT

# ── Authentication ──
JWT_SECRET=${JWT_SECRET}
ADMIN_USERNAME=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASS}
STREAMLIT_PASSWORD=${STREAMLIT_PASS}

# ── API Keys ──
OPENALEX_API_KEY=${OPENALEX_KEY}
SEMANTIC_SCHOLAR_API_KEY=${S2_KEY}
SME_EMAILS=${USER_EMAIL}

# ── Service URLs (internal Docker network) ──
QDRANT_URL=http://sme_qdrant:6333
OLLAMA_URL=http://sme_ollama:11434

# ── Ollama ──
# After setup, link your Ollama account:
#   docker exec -it sme_ollama ollama signin
EOF

# Set restrictive permissions (owner read/write only)
chmod 600 "$ENV_FILE"

echo ""
echo "Created .env file with permissions 600 (owner read/write only)"

# ── Step 7: Create Admin User (if Docker is available) ──
echo ""
if command -v docker &> /dev/null && docker info &> /dev/null; then
    read -p "Create admin user now? (requires Docker) (Y/n): " CREATE_ADMIN
    if [ "$CREATE_ADMIN" != "n" ] && [ "$CREATE_ADMIN" != "N" ]; then
        echo ""
        echo "Building containers..."
        docker compose build dashboard-backend

        echo ""
        echo "Creating admin user..."
        # Pass password via stdin to avoid exposing in process list
        echo "${ADMIN_PASS}" | docker compose run --rm -T dashboard-backend python -c "
import sys
from auth import create_user
password = sys.stdin.read().strip()
create_user('${ADMIN_USER}', password, 'admin')
print('Admin user created successfully')
"
        echo "Admin user '${ADMIN_USER}' created"
    fi
else
    echo "Docker not available. Admin user will be created on first 'docker compose up'."
    echo "Or run this after starting Docker:"
    echo "  docker compose run --rm dashboard-backend python -c \"from auth import create_user; create_user('${ADMIN_USER}', '<password>', 'admin')\""
fi

# ── Step 8: Summary ──
echo ""
echo "==========================================="
echo "  Setup Complete!"
echo "==========================================="
echo ""
echo "Next steps:"
echo "  1. Review .env file if needed"
echo "  2. Build containers:    docker compose build --no-cache"
echo "  3. Start the system:    docker compose up -d"
echo "  4. Link Ollama:         docker exec -it sme_ollama ollama signin"
echo "  5. Validate setup:      bash scripts/validate.sh"
echo ""
echo "Access points:"
echo "  Dashboard:  http://localhost:3030"
echo "  Streamlit:  http://localhost:8502"
echo ""
echo "IMPORTANT: The API keys you previously had in config files have been"
echo "migrated to .env. Consider rotating them at the provider websites"
echo "since they were previously exposed in plaintext."
echo ""
